### PR TITLE
Add JLink support

### PR DESCRIPTION
**Pull request by calvinatintel**
Need https://github.com/01org/CODK-A-ARC/pull/23 on `arc` directory to test.
Need https://github.com/01org/CODK-Z-Flashpack/pull/6 on `flashpack` directory test.

### CODE REVIEW

**Review by eriknyquist — APPROVED** [review]
uploading works fine. Can't test debug until the CODK-A-ARC PR is rebased.

**Comment by calvinatintel** [comment]
A-ARC PR fixed. Please review.

**Comment by eriknyquist** [comment]
approved... again? I guess?

**Comment by eriknyquist** [comment]
re-tested and it all still works

**Pull request merged**
