### PR TITLE
Add firmware, samples, and manifest

### PR DESCRIPTION
**Pull request by calvinatintel**
@bbaltz505 @bigdinotech Do you think this is the way we should organize M? Or should be make it monolithic like Z? Is it possible to make it monolithic considering that we need to mix Zephyr and Sketches?

### CODE REVIEW

**Comment by bbaltz505** [comment]
@calvinatintel I lean toward a single, monolithic repo - especially since we now download/install corelibs as a zip instead of cloning.

**Comment by SidLeung** [comment]
@bbaltz505 @calvinatintel Not sure if a single repo is desirable.  I think we may need one for the ARC core, one for the I86, and one for the Nordic core.  Consider the fact that we do not have a way to release the source code for the Nordic core yet, need to separate it out as an entity of its own.

**Comment by noelpaz** [comment]
IS Nordic just a binary not source code. If yes monolithic may work

**Comment by calvinatintel** [comment]
I prefer a single repo too. I'll rename this repo to `CODK-M`.

**Pull request closed without merging**
