### PR TITLE
Update Zephyr to 1.5.0

### PR DESCRIPTION
**Pull request by calvinatintel**
This change actually doesn't make any difference since the variable is not used inside `install-zephyr.sh`. Nonetheless, it should be updated so that it doesn't confuse the users.

### CODE REVIEW

**Review by bigdinotech — APPROVED** [review]
+1 though i think we should provide  a script or something that allows user to update/upgrade theie zephyr version without having to manually delete it

**Comment by eriknyquist** [comment]
Just testing now

**Review by eriknyquist — APPROVED** [review]
Agree with Dino, would be nice to have some 'zephyr-update' target, even if it's only a script that deletes & re-downloads

**Comment by calvinatintel** [comment]
Good suggestions on the upgrade target. I'll work on it next.

**Pull request merged**
