### PR TITLE
Update to Zephyr 1.6.0

### PR DESCRIPTION
**Pull request by bigdinotech**
-update zephyr version
-update zephyr sdk to 0.8.2

### CODE REVIEW

**Comment by bigdinotech** [comment]
@calvinatintel @eriknyquist please review.
Please do not merge until we finish porting x86-samples

**Comment by calvinatintel** [comment]
@yashaswini-hanji please review

**Review by yashaswini-hanji — COMMENTED** [review]
how to test this?

**Comment by poussa** [comment]
This PR seem to work. I tested it. Please merge asap. The main.c is already using Zephyr 1.6 APIs like k_thread_spawn so the tree is broken anyway.

**Pull request merged**
