### PR TITLE
Add README.md

### PR DESCRIPTION
**Pull request by eriknyquist**

### CODE REVIEW

**Comment by eriknyquist** [comment]
@calvinatintel @bbaltz505 @bigdinotech

**Comment by calvinatintel** [comment]
Let's make this our standard steps

```
git clone CODK-[A|M|Z]
cd $_
make clone
sudo make install-dep
make setup
make compile
make upload
```

Thoughts?

**Comment by bbaltz505** [comment]
can we include the clone target inside setup?
$(CODK_SW_DIR):
        git clone $(CODK_SW_URL) $(CODK_SW_DIR)

$(CODK_FW_DIR):
        git clone $(CODK_FW_URL) $(CODK_FW_DIR)

$(CODK_FLASHPACK_DIR):
        git clone $(CODK_FLASHPACK_URL) $(CODK_FLASHPACK_DIR)

$(CODK_CORELIBS_DIR):
        git clone $(CODK_CORELIBS_URL) $(CODK_CORELIBS_DIR)

setup: check-codk $(CODK_FW_DIR) $(CODK_SW_DIR) $(CODK_CORELIBS_DIR) $(CODK_FLASHPACK_DIR) \
       $(CODK_SW_DIR)/arc32 $(CODK_SW_DIR)/arduino-ide

**Comment by calvinatintel** [comment]
Ah, my mistake. It should be like this.

```
git clone CODK-[A|M|Z]
cd $_
sudo make install-dep
make setup
make compile
make upload
```

Using the directories as target is much cleaner. I'll make the changes.

**Comment by calvinatintel** [comment]
Can you base it on this? https://github.com/01org/CODK-A/blob/master/README.md

**Comment by eriknyquist** [comment]
Sure. Is there anything preventing us from putting "source ../zephyr/zephyr-env.sh" in the Makefile? If not, then can both READMEs be identical apart from the tree name?

**Comment by eriknyquist** [comment]
@calvinatintel how's that?

**Comment by calvinatintel** [comment]
Looks good to me

**Comment by calvinatintel** [comment]
cherry-picked

**Pull request closed without merging**
