### PR TITLE
Add upload-arc-jtag target

### PR DESCRIPTION
**Pull request by eriknyquist**
@bbaltz505 @calvinatintel please review and test.

### CODE REVIEW

**Comment by bbaltz505** [comment]
+1 works fine

**Comment by eriknyquist** [comment]
I'll do A and Z later, but need to get this in for now since it's really the only way to upload the mailbox examples (no cdc-acm). @calvinatintel please merge.

**Comment by eriknyquist** [comment]
@calvinatintel @bbaltz505 we need this today please merge

**Comment by bbaltz505** [comment]
merged

**Pull request closed without merging**
